### ISSUE TITLE
Global bloc/cubit instance access with named routes

### ISSUE THREAD

**Issue by andrui** [Iteo/hooked_bloc#74]
First of all my apologize for creating this issue, but I am newbie in Flutter and haven't found any information in th net. I hope you can help me.

Preconditions:
 - There is an app which uses named routing and multiple pages
 - App uses bloc, hooked_bloc and get_it + injectable

What I want to achieve is to have globally accessible bloc/cubit instance (let it be some UserData data bloc which is needed on all pages). I ahve used HookedBlocConfigProvider (as described in your example). But realized that each page creates new instance of the cubit. Then I have tried to mark cubit with "@singleton" instead of "@injectable", but got an error that I tried to emit value on disposed bloc. So the only way I was able to achieve the result is to provide "closeOnDispose: false" to every call of useBloc hook. This works but I am not sure that this is a true way. There are a lot of recepies how to do this directly with BlocProvider and BlocProvider.value() (e.g. enclose MaterialApp with BlocProvider) but there are no solutions at all how to share same instance of cubit to all or multiple specific routes/pages with hooked_bloc + get_it + injectable.

Is it possible to implement such solution somehow?
Thank you in advance!

**Comment by tomkad99** [comment]
Hi @andrui 

Sorry for a late response, we are quite busy right now.

One thing to mention is the current user data mostly should be accessible for any recreated cubit from another data source. So we should not tie data state with cubit state.

This approach allows cubits to be garbage collected along with pages, so no extra memory is kept. That's why there are no much examples how to do it.

Assuming that you really need that single, globally accessible cubit:
We agree that `@singleton` with flag `closeOnDispose: false` is one of proper solutions.

**Just do not forget to close that Cubit when it is not needed anymore.**
